---
# The Cluster object is the top level owner of all resources.
# It coordinates between the control plane and the infrastructure/machines.
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: GCPManagedCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    kind: GCPManagedControlPlane
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"
---
# Due to the nature of managed Kubernetes and the control plane implementation,
# the infrastructure provider for a GKE cluster is basically a no-op.
# It sets itself to ready as soon as it sees the control plane ready.
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPManagedCluster
metadata:
  name: "${CLUSTER_NAME}"
---
# The control plane abstracts readiness and provisioning of an GKE cluster.
# Because GKE requires a default pool, this also requires a reference to the
# default machine pool.
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPManagedControlPlane
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  version: "${KUBERNETES_VERSION}"
  project: "${GCP_PROJECT}"
  region: "${GCP_REGION}"
  network:
    name: "${CLUSTER_NAME}-network"
    subnetwork: "${CLUSTER_NAME}-subnet"
  defaultPoolRef:
    name: nodepool0
---
# We provision a default machine pool with no bootstrap data (GKE will provide it).
# We specify a GCPManagedMachinePool as the infrastructure machine, which
# will be reflected in GCP as node pools attached to a GKE cluster.
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: nodepool0
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: GCPManagedMachinePool
        name: nodepool0
        namespace: default
      version: ${KUBERNETES_VERSION}
---
# The GCP-specific machine pool implementation drives the configuration of the
# GKE node.
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPManagedMachinePool
metadata:
  name: nodepool0
spec:
  instanceType: "n1-standard-8"
  bootDiskSizeGB: 100
